### ISSUE TITLE
inheritance aware Value helpers

### ISSUE THREAD

**Issue by RonnyPfannschmidt** [jazzband/django-configurations#113]
for use with mixins and subclasses, it seems helpful to have some values that take the values of base classes into account

for example

```
class Base(Configuration):
    INSTALLED_APPS = values.Backend(...)

class Dev(Base):
  INSTALLED_APPS = values.Appender('debug_toolbar')

class Prod(Base):
   INSTALLED_APPS = values.Appender('myapp.specialerrors')
```

**Comment by jezdez** [comment]
Hm, not sure, this sounds quite magic, but maybe this is just another level of magic..

**Comment by pdehaye** [comment]
I think this would be helpful. I am surprised it has been here for so long. 

I suggest something like this syntax:

```
class Base(ViralConfiguration("INSTALLED_APPS", "MIDDLEWARE")):
  INSTALLED_APPS = values.Backend(...)

class Dev(Base):
  INSTALLED_APPS += values.ListValue(['debug_toolbar'])

class Prod(Base):
   INSTALLED_APPS += values.ListValue(['myapp.specialerrors'])
```

**Comment by RonnyPfannschmidt** [comment]
@pdehaye your proposed syntax is impossible to do in python since `INSTALLED_APPS` is not available in the new classes declaration namespace

**Comment by pdehaye** [comment]
depending on the python version, it is achievable through metaclasses.

**Comment by bittner** [comment]
I'm trying to deal with a similar use case in #217 (Mixins).

**Comment by RonnyPfannschmidt** [comment]
closing to get if off my plate on github
