### ISSUE TITLE
SecretValue validation problem

### ISSUE THREAD

**Issue by russelldavies** [jazzband/django-configurations#118]
Noticed this in recent HEAD version (5ece10704) in comparison to what is on PyPI.

I have a configuration setup with a Common class (which inherits from Configuration) and then Local and Production subclasses. The Production subclass has a `SecretValue` like so:

```
EMAIL_HOST_PASSWORD = values.SecretValue(environ_prefix=None, environ_name='SENDGRID_PASSWORD')
```

Even when `DJANGO_CONFIGURATION` is set to "Local", a `ValueError` is being thrown that the secret value must be set. Previous versions would only throw this error if the configuration was set to "Production". It seems that when `environ_name` is manually set, validation occurs when it shouldn't be.

Either the `Value.__call__` code should be fixed or `SecretValue` should have `late_binding = True` by default.

**Comment by mauricioabreu** [comment]
Are you still having this problem @russelldavies ?

**Comment by russelldavies** [comment]
Yep, still an issue.

**Comment by mauricioabreu** [comment]
@russelldavies using the latest version?

**Comment by russelldavies** [comment]
@mauricioabreu Yeah, I tried the version on PyPI (which is 1.0) and from the repo's HEAD (which is 1.0.1.dev0)

**Comment by mauricioabreu** [comment]
@russelldavies thanks for the information. We will debug this code and figure out what is happening.

**Comment by mauricioabreu** [comment]
Ok, I finally reproduced the error.

My thoughts on this is that this is not an error. It loads the classes and read/validate attribute by attribute. Secret values must be environment variables. And not having this one present (even using a different configuration class) will raise this error.

What is your opinion @russelldavies ?

**Comment by russelldavies** [comment]
It's handy for a handful of cases and means you don't need to define the variable again but I suppose it may be surprising for the behaviour to differ depending on environment. I don't have strong options on it though. 

I guess you could allow the `late_binding` option to be passed during variable declaration.

**Comment by mauricioabreu** [comment]
Thanks for the feedback @russelldavies 
I am going to debug it deeper to find a solution

**Comment by gerodp** [comment]
Hi,

I'm facing the same issue. I wonder if you have thought of any solution.

**Comment by skolsuper** [comment]
@gerodp I fixed this with the `late_binding` kwarg, suggested here:

https://github.com/jazzband/django-configurations/issues/96
