### ISSUE TITLE
Optionally disable validator for default values

### ISSUE THREAD

**Issue by blueyed** [jazzband/django-configurations#123]
With something like `URLValue` it might be useful to skip validating the default value, e.g.

    values.URLValue('/media/')

This can be achieved currently using a property:

    @property
    def MEDIA_URL(self):
        return values.URLValue('').value or '/media/'

But something like the following might be better:

    MEDIA_URL = values.URLValue('/media/', validate_default=False)

**Comment by mauricioabreu** [comment]
Could not it be achieved using values.Value?
https://django-configurations.readthedocs.org/en/stable/values/#default-behavior

`/media/` is not an URL at all. Am I missing something?

**Comment by blueyed** [comment]
Yes, using `values.Value` might be the way to go.

My use case was to enforce a valid URL, but falling back to a non-URL value.

**Comment by blueyed** [comment]
For what it's worth, I was using this:

```
@property
def MEDIA_URL(self):
    """Validate env setting, but default to /media/."""
    return values.URLValue(default='', environ_prefix='',
                           environ_name='DJANGO_MEDIA_URL') or '/media/'
```
