### ISSUE TITLE
Is a new release planned anytime soon?

### ISSUE THREAD

**Issue by mcastle** [jazzband/django-configurations#125]
Master has some great improvements. Would be nice if these were available in a new release.

**Comment by slafs** [comment]
You'd probably want to read comments on commit 0ff4c7612 and specially this one https://github.com/jezdez/django-configurations/commit/0ff4c7612d28036449edd4b2cf3b58ca1eded0f2#commitcomment-13412719

**Comment by powellc** [comment]
Given that that was nearly 6 months ago at this point ... :( Tired of having to use git in my setup.py file ... it's really hacky.

**Comment by blueyed** [comment]
This project is now managed by https://jazzband.co/ and we will have a release soon.
You can be a part of it, by joining the Jazzband and helping out.

**Comment by blueyed** [comment]
Closing this in favour of #132.

**Comment by mcastle** [comment]
:+1:  Thanks!
