### ISSUE TITLE
Tests only run on Py35?

### ISSUE THREAD

**Issue by daddz** [jazzband/django-configurations#137]
Hey I'm not sure if you noticed it but the tests seem to run on Python 3.5 only according to the logs: e.g. https://travis-ci.org/jazzband/django-configurations/jobs/100094955#L98 for py26-dj14

Complete list: https://travis-ci.org/jazzband/django-configurations

Is this a bug in display or bad configuration?

**Comment by mauricioabreu** [comment]
I think tests are running for every version described there. It is not just verbose.

**Comment by jezdez** [comment]
What @mauricioabreu said, this is just a misleading log due to the way we integrate tox and Travis CI. I increased the tox verbosity in https://github.com/jazzband/django-configurations/commit/8e2eb88ef16c4f3a2e515d62e5902b0a68fad54f.
