### ISSUE TITLE
Update doc examples for Django 1.9+ settings now using lists rather than tuples

### ISSUE THREAD

**Issue by abbottc** [jazzband/django-configurations#140]
The ["Global Settings Defaults" section of the docs] (http://django-configurations.readthedocs.org/en/stable/patterns/#global-settings-defaults) has code examples like:

     Configuration.LANGUAGES + (('tlh', 'Klingon'),)

Perhaps it would be useful for the docs to note that Django 1.9+ uses lists rather than tuples for these settings, and would instead need to be:

     Configuration.LANGUAGES + [('tlh', 'Klingon')]

...otherwise an error would result about not allowing concatenation between lists and tuples.

**Comment by blueyed** [comment]
Thanks for the report!
Fixed by merging #141.
