### ISSUE TITLE
Unable to start django server if celery instance is defined according to cookbook 1.0 Windows 8.1

### ISSUE THREAD

**Issue by IronLemon** [jazzband/django-configurations#145]
I use django 1.8.8, celery 3.1.20 and django-configurations 1.0. Windows 8.1
If I define celery instance according to cookbook [http://django-configurations.readthedocs.org/en/latest/cookbook/#id4](url) I am unable to start django dev server. 
It just freezes, nothing happens

Here is my celery.py

```
from __future__ import absolute_import
import os

from celery import Celery
from django.conf import settings

os.environ.setdefault('DJANGO_SETTINGS_MODULE', 'common.settings')
os.environ.setdefault('DJANGO_CONFIGURATION', 'Dev')

import configurations
configurations.setup()

celery_broker_connection = 'redis://{0}:{1}/{2}'.format(
    settings.REDIS['host'], settings.REDIS['port'], settings.REDIS['db'])
celery_app = Celery('jobs', backend=celery_broker_connection, broker=celery_broker_connection)

celery_app.config_from_object('django.conf:settings')
celery_app.autodiscover_tasks(lambda: settings.INSTALLED_APPS)
```

Then if I use celery cookbook ver 0.8 [http://django-configurations.readthedocs.org/en/0.8/cookbook/#id4](url)
```
...
from configurations import importer
importer.install()
...
```
 django server starts correctly but I get endless stream of errors from celery worker like this 
`[2016-01-28 11:42:43,256: ERROR/MainProcess] Process 'Worker-8' pid:13656 exited with 'exitcode 1'`

Perhaps these two issues are not related to each other. 

Also the second issue is being reproduced on django 1.7 and django-configurations 0.8 on Windows. (on Ubuntu 14.04 everything is fine). If do not use django-configurations then django server and celery worker start and work correctly. So I decided that it's related to django-configuration.

Does anybody know what it can be? Thanks in advance!

**Comment by blueyed** [comment]
See https://github.com/jazzband/django-configurations/issues/196 for some followup.
