### ISSUE TITLE
Multiple caches

### ISSUE THREAD

**Issue by peterbe** [jazzband/django-configurations#170]
Doing
```
CACHES = values.CacheURLValue(...)
```
is nice in that it automatically wraps `django-cache-url` so I can just supply a URL. 
But makes it impossible to do multiple caches. By overriding `alias` I can change it from "default" but can't have "default" **and** "someotherkey".
@amureki [suggested](https://github.com/jazzband/django-configurations/issues/161#issuecomment-238536440) you write a callable property. But then I lose the value of what `values.CacheURLValue` offers.

**Comment by peterbe** [comment]
I tried this:
```python
    @property
    def CACHES(self):
        caches = {
            'default': values.CacheURLValue(
                'redis://redis-cache:6379/1',
                environ_name='REDIS_URL',
            ),
            'persistent': values.CacheURLValue(
                'redis://redis-store:6379/1',
                alias='persistent',
                environ_name='REDIS_STORE_URL',
            )
        }
        return caches
```

But when you inspect it, it's not "hydrated". I.e.
```
>>> django.conf import settings
>>> type(settings.CACHES['default'])
<class 'configurations.values.CacheURLValue'>
```

**Comment by peterbe** [comment]
Seems very related: https://github.com/jazzband/django-configurations/issues/97

**Comment by peterbe** [comment]
Here's how I ended up solving it:
```python
    CACHES = {
        'default': django_cache_url.config(
            default='redis://redis-cache:6379/1',
            env='REDIS_URL',
        ),
        'store': django_cache_url.config(
            default='redis://redis-store:6379/1',
            env='REDIS_STORE_URL',
        )
    }

```

**Comment by bittner** [comment]
We should add @peterbe's solution to the docs via https://github.com/jazzband/django-configurations/issues/36#issuecomment-445610301.

**Comment by hugobrilhante** [comment]
For handling multiple caches with django-configurations, this approach works well:

```python

CACHES = {
    'default': values.CacheURLValue('redis://default:6379/0').value['default'],
    'secondary': values.CacheURLValue('redis://secondary:6379/1').value['default']
}
```

**Why this works:**
- Clean separation of cache backends
- Uses the existing `CacheURLValue` system
- Configurable via environment variables
- Maintains standard Django cache structure

Example output:
```python
{
    'default': {'BACKEND': '...RedisCache', 'LOCATION': 'redis://default:6379/0'},
    'secondary': {'BACKEND': '...RedisCache', 'LOCATION': 'redis://secondary:6379/1'}
}
```
