### ISSUE TITLE
Appending INSTALLED_APPS

### ISSUE THREAD

**Issue by c0yote** [jazzband/django-configurations#171]
I would like to conditionally add `django_extensions` to the INSTALLED_APPS list, but only when using my Development configuration.

I have a Development and Production configuration that derive from a Base.

What is the intended way of appending something like that using `django-configurations`?

**Comment by blueyed** [comment]
You can use `setup` for that:
```python
from configurations import Configuration

class Development(…, Configuration):
    @classmethod
    def setup(cls):
        super().setup()
        cls.INSTALLED_APPS += ('django_extensions',)
```

**Comment by c0yote** [comment]
Thanks.

**Comment by bittner** [comment]
Note that [INSTALLED_APPS](https://docs.djangoproject.com/en/2.1/ref/settings/#installed-apps) is now a list in Django.
