### ISSUE TITLE
Redis equivalent of DatabaseURLValue?

### ISSUE THREAD

**Issue by lwm** [jazzband/django-configurations#172]
We have a `DatabaseURLValue()` which uses `dj_database_url`.

What about something for Redis that uses `dj_redis_url`?  That'd be cool. 

Right now, I just do:

``` python
REDIS_URL = values.Value()
```

If we're agreed, will submit a PR for it.

**Comment by blueyed** [comment]
Not sure if it's worth the overhead (of installing some package etc) - since Redis URLs are simpler in general and have no password even often.
But then it is your (or the user's) decision.. ;)
I'm +0.

([for reference](https://github.com/dstufft/dj-redis-url/blob/master/dj_redis_url.py))

**Comment by lwm** [comment]
Oh, you can already do it with https://github.com/ghickman/django-cache-url and `CacheURLValue`.
