### ISSUE TITLE
Documentation for #62/51

### ISSUE THREAD

**Issue by lwm** [jazzband/django-configurations#173]
Following from https://github.com/django/asgi_redis/issues/52, I just added `environ_name="REDIS_URL"` and things worked. I saw that #62 was related or? Did the documentation go missing for that then (#51)? I'm not even sure what `environ_name=foo` does/means? Will submit a PR is someone can shed some light, thanks :+1:

**Comment by lwm** [comment]
From #62:

> The aim with that idea is that Value instances can now be used independently from the configuration context as long as wished and properly configured (means the environ_name is given). In addition Values instances now cache their environment value to be accessible without calling setup_value once again.

I'm not sure? And I saw [in the docs](https://django-configurations.readthedocs.io/en/stable/values/#custom-environment-variable-names):

> To support legacy systems, integrate with other parts of your software stack or simply better match your taste in naming public configuration variables, django-configurations allows you to use the environ_name parameter of the Value class to change the base name of the environment variable it looks for. For example this would enforce the name DJANGO_MYSITE_TZ instead of using the name of the Value instance.:

But, really, I'm still not sure here haha

**Comment by blueyed** [comment]
IIRC `environ_name` has different defaults, e.g. with/without `DJANGO_` prefix etc.
You do not say where you've added `environ_name`.

It seems to be related to `late_binding` after all (also): https://github.com/jazzband/django-configurations/blob/a606003c777160fe6141acb9386d0e217c62dd3c/configurations/values.py#L45-L58

**Comment by lwm** [comment]
> You do not say where you've added environ_name.

Ah, I used it [over here](https://github.com/giving-a-fuck-about-climate-change/carbondoomsday/blob/master/carbondoomsday/settings.py#L141).

> It seems to be related to late_binding after all (also): https://github.com/jazzband/django-configurations/blob/a606003c777160fe6141acb9386d0e217c62dd3c/configurations/values.py#L45-L58

Ah right. OK, so the docstring has it (from https://github.com/jazzband/django-configurations/commit/3f892f9814757b171d2f93500a609486d0a9ff27):

> checks if the creation can end up directly in the final value.
> That is the case whenever environ = False or environ_name is given.

I think I have it now. I'll add a note to the documentation.

:+1:

**Comment by lwm** [comment]
Oh, I think we need to add a similar fix to https://github.com/jazzband/django-configurations/commit/3f892f9814757b171d2f93500a609486d0a9ff27 for this case:

``` python
>>> type(values.Value([], environ=False))
<class 'configurations.values.Value'>
>>> type(values.Value([1], environ=False))
<class 'list'>
```
