### ISSUE TITLE
Is there a planned release for Django 2.0 Support?

### ISSUE THREAD

**Issue by W7PEA** [jazzband/django-configurations#195]
Hey there,

PyPi shows 2.0 released on Jul 29, 2016 and I see a PR to suport Django 2.0 https://github.com/jazzband/django-configurations/pull/182 on Sep 30, 2017. 

Is there a planned release coming up to get official DJ2.0 support live?

Thanks so much!

**Comment by joshua-s** [comment]
This is badly needed

**Comment by blueyed** [comment]
Closing in favor of https://github.com/jazzband/django-configurations/issues/203.

Master should be working with 2.1

A PR with a changelog (shouldn't be too hard) would certainly help.
