### ISSUE TITLE
documents show PositiveInteger values function, but it does not exist?

### ISSUE THREAD

**Issue by lanshark** [jazzband/django-configurations#199]
The documentation (https://django-configurations.readthedocs.io/en/latest/values/) shows a 

PositiveIntegerValue() function

But that function does not exist.

AH! it's in the commits, but apparently not yet released.

**Comment by amureki** [comment]
Hi @lanshark !

Thanks for the issue.
Yes, this feature was added in #186, but package was not released since that time.

@blueyed do you think we can issue a new release somehow?

**Comment by blueyed** [comment]
Sure, we should go probably the jazzband route: https://jazzband.co/about/releases

**Comment by blueyed** [comment]
2.1 has been released.
