### ISSUE TITLE
Usage in README is not included in docs

### ISSUE THREAD

**Issue by jxltom** [jazzband/django-configurations#215]
The docs does not include the basic usage of django-configurations which is explained in github's README.

It will be nice to add content of README to docs.

**Comment by bittner** [comment]
Are you sure? The ["Quickstart" section is included](https://django-configurations.readthedocs.io/en/latest/), which tells me that the [README is included](https://raw.githubusercontent.com/jazzband/django-configurations/master/docs/index.rst) in the docs (with line 1 of `index.rst`).

Is there anything I'm missing?

**Comment by jxltom** [comment]
Oh, thanks! I missed that. It is not just not shown in the TOC, so I didn't find it. :sob:
