### ISSUE TITLE
Values will not raise ValueError

### ISSUE THREAD

**Issue by raratiru** [jazzband/django-configurations#225]
```
>>> from configurations import values
>>> negative_float = -8.5
>>> type(negative_float)
<class 'float'>
>>> values.PositiveIntegerValue(negative_float)
 -8.5
```
Should'nt it raise an error instead?

**Comment by blueyed** [comment]
Yeah.

/cc @MikeWooster

**Comment by blueyed** [comment]
Please consider creating a PR with a fix and test.

**Comment by raratiru** [comment]
I would very much like to contribute, I do not understand how to run the existing tests in the local copy of the forked repository.

**Comment by blueyed** [comment]
Try `tox -e py37-dj21` (or some other environment if you do not have py37).
See `tox -e py37-dj21 -- --help` then for options, e.g. to select a test label (it is using Django's test runner, not pytest unfortunately).

**Comment by raratiru** [comment]
I have added some failing tests with #227 

[`CastingMixin`][1] and [`ValidationMixin`][2] hide elements of validation that could provide a useful result when joined together and add in the game the `RegexValidator` for example.

Out of the box doing something like `IntegerValue(ValidationMixin, CastingMixing, Value)` will not be effective due to their `to_python` methods that behave completely differently and are not related with a `super()` function because this is not feasible due to the inheritance hierarchy:

[ValidationMixin().init()][3] will call [`CastingMixin().to_python()`][4].

On the other hand I am not familiar with the range of occasions where each of those Mixins is playing a crucial part, so overriding one of them or creating one of my own, for `IntegerValue` to use, would be a giant step.

[1]: https://github.com/jazzband/django-configurations/blob/ec56685da47c32b1bbc15e25a622d1e5529e6d82/configurations/values.py#L145-L174
[2]: https://github.com/jazzband/django-configurations/blob/ec56685da47c32b1bbc15e25a622d1e5529e6d82/configurations/values.py#L339-L359
[3]: https://github.com/jazzband/django-configurations/blob/ec56685da47c32b1bbc15e25a622d1e5529e6d82/configurations/values.py#L351
[4]: https://github.com/jazzband/django-configurations/blob/ec56685da47c32b1bbc15e25a622d1e5529e6d82/configurations/values.py#L167

**Comment by raratiru** [comment]
#227 Is successfully passing.
