### ISSUE TITLE
Remove Python 2.7 support

### ISSUE THREAD

**Issue by pauloxnet** [jazzband/django-configurations#245]
[Official support for Python 2.7 ends in two months](https://pythonclock.org/), after which no bug fixes or security updates will be released. In preparation for that, I think it is time to remove code from Django Configuration related to Python 2.7, as well as removing Python 2.7 from the CI test matrix.

The following checklist can tracks the progress of this endeavour:

- [x] remove Python 2 support in `.travis.yml` and `tox.ini`
- [x] remove Python 2 classifiers in `setup.py`
- [x] remove `six` from the code
- [x] remove `__future__` statements from the code
- [x] update `README.rst` and `docs/` accordingly
- [x] remove comments related to Python 2  from the code

**Comment by graingert** [comment]
@pauloxnet is this worth revisiting? there's a tool https://github.com/asottile/pyupgrade that can automated a lot of these steps

**Comment by pauloxnet** [comment]
@graingert I think `pyupgrade` has already been used in this commit: https://github.com/jazzband/django-configurations/commit/6cb932e47f1763f0dcdd0c1f838236997772b351

**Comment by graingert** [comment]
looks like this issue should be closed @auvipy https://github.com/jazzband/django-configurations/pull/264

**Comment by pauloxnet** [comment]
All steps are been done, I've just checked. I'm going to close it.

**Comment by auvipy** [comment]
thanks
