### ISSUE TITLE
Use tox-travis for Travis configuration

### ISSUE THREAD

**Issue by johnfraney** [jazzband/django-configurations#246]
The current TravisCI configuration (`.travis.yml`) is difficult to keep in sync with the Tox configuration (`tox.ini`). [tox-travis](https://github.com/tox-dev/tox-travis) is an official Travis plugin that helps configure Travis to use the Python envs declared in `tox.ini`.

This would make the Travis configuration file much easier to maintain.

**Comment by jezdez** [comment]
Yeah, totally agreed. I'll do this now.
