### ISSUE TITLE
Release version 2.2 on pypi

### ISSUE THREAD

**Issue by pauloxnet** [jazzband/django-configurations#247]
Please release version django-configurations 2.2 with support to django 3.0 released today because django-configuration 2.1 is broken with django 3.0

I tried to tag a v2.2 version following this instructions
https://jazzband.co/about/releases#continuous-integration
but something didn't work so I removed the tag.

@jezdez can you tag version 2.2 and release it on pypi ?

**Comment by jezdez** [comment]
Yeah, I'll do that later.

**Comment by pauloxnet** [comment]
Thanks.

**Comment by jezdez** [comment]
So yeah, @blueyed broke the deployment a while ago: https://github.com/jazzband/django-configurations/pull/209#issuecomment-561082938

**Comment by pauloxnet** [comment]
So what can we do now to help with the release of django-configuration 2.2 ?

**Comment by jezdez** [comment]
I'm working right now on moving the travis/tox config to tox-travis (#246) and then do the release. It'll happen in the next few hours.

**Comment by pauloxnet** [comment]
Ok, thanks !

**Comment by jezdez** [comment]
[2.2](https://pypi.org/project/django-configurations/2.2/) is out.

**Comment by pauloxnet** [comment]
Thanks for the release.
