### ISSUE TITLE
Docs: section 'Read .env file' missing on readthedocs.io

### ISSUE THREAD

**Issue by casio** [jazzband/django-configurations#266]
Looking at https://django-configurations.readthedocs.io/en/stable/cookbook/ the section on `DOTENV` usage is missing, although its clearly there in the repo: https://github.com/jazzband/django-configurations/blob/master/docs/cookbook.rst#read-env-file

![image](https://user-images.githubusercontent.com/29784/97430691-8e776c00-1919-11eb-8f83-c8afb3591495.png)

**Comment by blueyed** [comment]
Not yet released - it is visible in "latest": https://django-configurations.readthedocs.io/en/latest/cookbook/
