### ISSUE TITLE
Release version 2.3 on pypi

### ISSUE THREAD

**Issue by pauloxnet** [jazzband/django-configurations#277]
I think its time to release a new version with support for Django 3+ and Python 3.6+

---

* [x] #315 
* [x] #309
* [x] #310
* [x] #319 
* [x] #320 
* [x] Publish release: https://github.com/jazzband/django-configurations/releases/tag/untagged-6ba2bc9f41d4148913fc
* [ ] Get Project Lead to push to PyPI: https://github.com/jazzband/help/issues/254

**Comment by fronbasal** [comment]
Bump

**Comment by jezdez** [comment]
This is done. Thanks, y'all!

**Comment by pauloxnet** [comment]
> This is done. Thanks, y'all!

@jezdez there's a way to trigger a new build on RTD to update the docs ?

**Comment by jezdez** [comment]
Will check when I'm back at the computer in a few hours.

**Comment by jezdez** [comment]
Oooookay, I think together with @brianhelba's #311 I think this should be working again.

**Comment by pauloxnet** [comment]
> Oooookay, I think together with @brianhelba's #311 I think this should be working again.

Yes, It worked ,thanks
https://django-configurations.readthedocs.io/en/2.3.1/changes.html

**Comment by pauloxnet** [comment]
I shared about the release of this new version on Twitter 🐦
https://twitter.com/pauloxnet/status/1457806192571465732
