### ISSUE TITLE
Make new releases on github

### ISSUE THREAD

**Issue by dmwyatt** [jazzband/django-configurations#278]
I found myself moving away from using django-configurations over 2020, because every time I looked at the front page of the repo, I saw:

![image](https://user-images.githubusercontent.com/163359/106488757-a65f0e80-6479-11eb-95b9-a109d3157ff3.png)

I tend towards avoidance of libraries that don't get much maintenance, and this kept tripping me up!

**Comment by blueyed** [comment]
Just for reference: there's a newer tag/release (for 2.2), which is not created as a proper GitHub release: https://github.com/jazzband/django-configurations/releases.

**Comment by blueyed** [comment]
2.2 was added to the GitHub releases: https://github.com/jazzband/django-configurations/releases/tag/2.2
