### ISSUE TITLE
Unable to set DEFAULT_AUTO_FIELD from settings since version 2.3.1

### ISSUE THREAD

**Issue by jbpenrath** [jazzband/django-configurations#323]
Since version 2.3.1, set `DEFAULT_AUTO_FIELD` from settings has no effect so warning `models.W042` appears during migrations.

It seems commit https://github.com/jazzband/django-configurations/commit/40bdab3f4ad3324a079e6bbeb1f1efee1469fede add `DEFAULT_AUTO_FIELD` into a `deprecated_settings` dict. In this way, we are not able anymore to set `DEFAULT_AUTO_FIELD` from a configuration as this property is deleted.

### Steps to reproduce:
- In your settings file add
`DEFAULT_AUTO_FIELD = "django.db.models.AutoField"`

- Then try to launch a migrate
`python manage.py migrate`

- You should see warnings `models.W042` in your console.

**Comment by rnegron** [comment]
This is also happening to us! Rolling back to `2.3` did not solve the issue, but going back to `2.2` did.

**Comment by ticosax** [comment]
I think we got hit by the same bug,
hopefully this will do https://github.com/jazzband/django-configurations/pull/327

**Comment by blueyed** [comment]
#327 has been merged, closing.

**Comment by ticosax** [comment]
released as https://pypi.org/project/django-configurations/2.3.2/
