### ISSUE TITLE
Using a custom DB engine with DatabaseURL

### ISSUE THREAD

**Issue by michaeltinsley** [jazzband/django-configurations#335]
Is there anyway to specify the DB engine to use when using DatabaseURL?

The use case I have is a non-standard DB engine, namely [django-timescaledb](https://github.com/schlunsen/django-timescaledb).

But, using DatabaseURL with this will default to the "django.db.backends.postgresql" engine, however, it looks like [dj-database-url allows this to be overridden with the engine parameter](https://github.com/jazzband/dj-database-url/blob/66bf06166574134134f7d31744907a86e5a52f9f/dj_database_url.py#L71). However this isn't surfaced within django-configurations from what I can tell?

Has anyone come across this use case before? Is there currently a good solution or am I missing something?

**Comment by lino** [comment]
Hi,

I have submitted a PR regarding this and I will continue the work in this project as well.

https://github.com/jazzband/dj-database-url/pull/174

**Comment by michaeltinsley** [comment]
@lino - Awesome, thank you 👍

**Comment by lino** [comment]
And the Pull request was just merged.
