### ISSUE TITLE
<frozen importlib._bootstrap>:1049: ImportWarning: ConfigurationImporter.find_spec() not found; falling back to find_module()

### ISSUE THREAD

**Issue by rrauenza** [jazzband/django-configurations#361]
I'm upgrading my project to python 3.11.3 and one of the things I am seeing is this deprecation warning --

Is this something the team is already aware of?  Am I right to assume its a warning with your project and not mine?

This may have been introduced with 3.10?

> Starting in this release, there will be a concerted effort to begin cleaning up old import semantics that were kept for Python 2.7 compatibility. Specifically, [find_loader()](https://docs.python.org/3.10/library/importlib.html#importlib.abc.PathEntryFinder.find_loader)/[find_module()](https://docs.python.org/3.10/library/importlib.html#importlib.abc.Finder.find_module) (superseded by find_spec()), [load_module()](https://docs.python.org/3.10/library/importlib.html#importlib.abc.Loader.load_module) (superseded by [exec_module()](https://docs.python.org/3.10/library/importlib.html#importlib.abc.Loader.exec_module)), [module_repr()](https://docs.python.org/3.10/library/importlib.html#importlib.abc.Loader.module_repr) (which the import system takes care of for you), the __package__ attribute (superseded by __spec__.parent), the __loader__ attribute (superseded by __spec__.loader), and the __cached__ attribute (superseded by __spec__.cached) will slowly be removed (as well as other classes and methods in [importlib](https://docs.python.org/3.10/library/importlib.html#module-importlib)). [ImportWarning](https://docs.python.org/3.10/library/exceptions.html#ImportWarning) and/or [DeprecationWarning](https://docs.python.org/3.10/library/exceptions.html#DeprecationWarning) will be raised as appropriate to help identify code which needs updating during this transition.

**Comment by PeterJCLaw** [comment]
See also:
- https://github.com/jazzband/django-configurations/issues/190
- https://github.com/jazzband/django-configurations/issues/358

**Comment by gump** [comment]
This is just awaiting a release to PyPI and was resolved in #365

**Comment by pauloxnet** [comment]
@rrauenza version 2.5 has been released. Can you confirm that this issue can be closed?

**Comment by rrauenza** [comment]
yes, thank you!!
