### ISSUE TITLE
Release 2.4.2 is not on PyPI

### ISSUE THREAD

**Issue by washeck** [jazzband/django-configurations#367]
The release was tagged in GitHub but it is not uploaded to PyPI.

**Comment by mzakarian** [comment]
any updates?
our upgrade to python 3.12 is blocked because of this

**Comment by olegchigirin** [comment]
Same here.

**Comment by washeck** [comment]
As https://github.com/jazzband/django-configurations/pull/369 is merged now, I believe @pauloxnet can release 2.5 with python 3.12 support. If there is anything I can do to help with that, let me please know.

**Comment by pauloxnet** [comment]
I'll try to work on the release today during the sprints of the DjangoCon US 2023

**Comment by pauloxnet** [comment]
I released version 2.5 yesterday but I can't see a new version on PyPi. I'm traveling back home from DjangoCon US 2023 can someone try to investigate in the logs of the release pipeline?

**Comment by jezdez** [comment]
Released 2.4.2 and 2.5 to PyPI

**Comment by pauloxnet** [comment]
Thanks @jezdez 🤗
I thought publishing to PyPi was automatic for a release.  I understand you have to do it by hand?

**Comment by jezdez** [comment]
> Thanks @jezdez 🤗

No problem!

> I thought publishing to PyPi was automatic for a release. I understand you have to do it by hand?

Not by hand, when the release is pushed to the Jazzband Package Index upon git tag/github release via the release GitHub Action, the project leads get an email asking to verify the release. Once that verification is done, they can push it to PyPI with a press of a button, confirming that it's good to go. The verification step is needed as a defense against malicious releases, given Jazzband's very open contributor patterns.

**Comment by pauloxnet** [comment]
Thanks for the explanation. It can be very useful to add it into the jazz and website, as a reference for the future. I'm sorry if it is already there. 😅
