### ISSUE TITLE
Apache, mod_wsgi, Enironment Variables

### ISSUE THREAD

**Issue by schacki** [jazzband/django-configurations#53]
I found the following comment "Environment variables for configuration (This won't work with Apache/mod_wsgi)." at pydanny's https://github.com/pydanny/cookiecutter-django.

Since this surprised me, I opened a ticket: https://github.com/pydanny/cookiecutter-django/issues/74. Pydanny replied correctly, that any solution for that is outside of the scope of the django project template. 

Now I fully understand that the root cause for this issue is NOT related to django-configurations. But as a result, the purpose of django-cofigurations (especially in combination with envdir) is somehow corrupted with mod_wsgi and Apache.  So I am wondering, if we can come up with some kind of workaround for the problem. 

The root cause is desciribed here: http://httpd.apache.org/docs/2.2/env.html. Grahame Dumpleton has commented on the issue at SO (last anwer):  http://stackoverflow.com/questions/19754834/access-apache-setenv-variable-from-django-wsgi-py-file

One workaround is described the the same SO question or also in this post: http://drumcoder.co.uk/blog/2010/nov/12/apache-environment-variables-and-mod_wsgi/. Though Graham had a very clear negative opinion on that. Still would that be a valid option?

Are there any other options? If not so, I would at leat propose to add a section to the cookbook in the docs about mod_wsgi/Apache.

**Comment by jezdez** [comment]
@pydanny Thanks!

I'm a bit sad to see this issue being dragged between that many project and that some people involved seem to be passive-aggressive about it. That said, it seems to be an issue for some users stuck on Apache so I'll take a look at how to best document it. Probably with the idea of having separate `wsgi/*.py` files to set the environment variables for each environment. It's an additional chore for the users but that's the gist of my experience with Apache anyway.

**Comment by pydanny** [comment]
@jezdez, Sending you a private email.
