### ISSUE TITLE
Django master issue with django.core.management.LaxOptionParser

### ISSUE THREAD

**Issue by pelme** [jazzband/django-configurations#65]
django.core.management.LaxOptionParser was removed in https://github.com/django/django/commit/856863860352aa1f0288e6c9168a0e423c4f5184

It is used by django-configurations and needs to be replaced in order for django-configurations to be compatible with recent django master.

I found this issue when running the pytest-django test suite, here is the full output:
https://travis-ci.org/pelme/pytest_django/jobs/28991234

**Comment by delgermurun** [comment]
@jezdez Hello,

When will you release this fix to pypi?

Thank you for your great job.
