### ISSUE TITLE
How to run scripts outside of Django?

### ISSUE THREAD

**Issue by jonathanng** [jazzband/django-configurations#93]
Sometimes, I like to access my models outside of Django. Usually I do something like this

    import os
    os.environ.setdefault("DJANGO_SETTINGS_MODULE", "mysite.settings")

    import django
    django.setup()

    import myapp
    instances = myapp.models.ModelOne.objects.all()

Now that I have installed django-configurations, I get the error:

     ImproperlyConfigured: django-configurations settings importer wasn't correctly installed. Please use one of the starter functions to install it as mentioned in the docs: http://django-configurations.readthedocs.org/

I tried adding something like this, but it still doesn't work.

    os.environ.setdefault('DJANGO_CONFIGURATION', 'Dev')

**Comment by destos** [comment]
+1, having a hard time getting configurations to work with scrapy and it's djangoitem.

**Comment by jezdez** [comment]
There is a `configurations.setup()` now that handles this, it's just not documented and released yet ;)

**Comment by juanriaza** [comment]
any update on this?

**Comment by MBARIMike** [comment]
I'm struggling too on getting configurations to work in a stand-alone database load script. Is there any guidance on how to use it?  I tried:

    from configurations import Configuration
    Configuration.setup()

before importing my models, but get this:

    class Local(Common):
    File ".../lib/python2.7/site-packages/configurations/base.py", line 30, in __new__
    raise ImproperlyConfigured(install_failure)
    django.core.exceptions.ImproperlyConfigured: django-configurations settings importer wasn't correctly installed. Please use one of the starter functions to install it as mentioned in the docs: http://django-configurations.readthedocs.org/

**Comment by MBARIMike** [comment]
After examining the configurations source code I came up the the solution of adding these lines before importing my model classes:

    # Must install config and setup Django before importing models
    from configurations import importer
    importer.install()
    # django >=1.7
    try:    
        import django   
        django.setup()          
    except AttributeError:          
        pass                     

A better install_failure message would have helped discover this solution (there is no mention of "starter functions" in the docs at http://django-configurations.readthedocs.org/).

**Comment by urkh** [comment]
Any update?

**Comment by urkh** [comment]
they can try with django-extensions, this work for me

http://django-extensions.readthedocs.org/en/latest/runscript.html

**Comment by mauricioabreu** [comment]
#142 is intended to guide users on how to run standalone scripts.

**Comment by blueyed** [comment]
#142 is merged, I assume this can be closed.
