### ISSUE TITLE
Unclear how to setup multiple databases

### ISSUE THREAD

**Issue by wldcordeiro** [jazzband/django-configurations#97]
I've been trying to use django-configurations and dj-database-url together to connect to multiple databases.

I've tried this and other variations, most gave me errors but this failed silently. How would you go about doing it correctly and can it be documented?

```py
DATABASES = values.DatabaseURLValue(
    default='postgres://user:password@localhost:5432/dbname',
    dbtwo='postgres://user:password@localhost:5432/dbname2',
)
```

**Comment by pydanny** [comment]
The idea behind `django-configuration` is based around the idea of the 12-factor setup, which includes the idea of smaller projects serving as architecture rather than larger, more encompassing projects. Because of this, django-configurations does not currently handle multi-db setups.

In the short term, I would add `os.environ.get()` to mitigate this issue.

In the long term, perhaps `django-configurations` would accept a `values.MultiDatabaseURLValues()` control as a pull request.

**Comment by wldcordeiro** [comment]
@pydanny thanks for the response, I might try adding the PR for MultiDatabaseURLValues, the project I was having issues with ended up working with a single database and celery.

**Comment by MBARIMike** [comment]
Would a reasonable pattern be to set DJANGO_DB_USER and DJANGO_DB_PASSWORD environment variables, pull them in with SecretValue() and construct the DATABASES dictionary from a list of databases that can be kept in the config file?

**Comment by remeika** [comment]
I decided to install the [DJ-Database-URL](https://github.com/kennethreitz/dj-database-url)  package, upon which DatabaseURLValue is modeled. It provides the option to override the environment variable that stores the database URL:

```python
from configurations import Configuration, values
import dj_database_url

class Base(Configuration):
    DATABASES = {
        "primary": dj_database_url.config(env='DJANGO_DB_PRIMARY_URL'),
        "warehouse": dj_database_url.config(env='DJANGO_DB_WAREHOUSE_URL'),
    }
    DATABASES["primary"]["HAS_HSTORE"] = True
    DATABASES["warehouse"]["HAS_HSTORE"] = True
```

I think it would be really nice/elegant if django-configurations adopted the `env` parameter to DatabaseURLValue; I would really love to remove those pesky `DJANGO_` prefixes.

And one small feature suggestion, probably best registered at DJ-Database-URL: It would be really really great to provide arbitrary DB parameters (like the PostgreSQL-specific `HAS_HSTORE` above) as query parameters in the URL. This could also apply to other url schemes like cache and search...

**Comment by wldcordeiro** [comment]
I'd like it if the DatabaseURLValue could do something like this `DATABASES = values.DatabaseURLValue([('default', 'postgres://myuser@localhost/mydb'), ('alternate', 'postgres://myuser@localhost/mydb2')])`

**Comment by jdharms** [comment]
We worked around this by making ````DATABASES```` a list and adding something like this to the end of our config file:

````python
@classmethod
    def setup(cls):
        super().setup()
        if isinstance(cls.DATABASES, list):
            cls.DATABASES = {
                list(item.value.keys())[0]:item.value[list(item.value.keys())[0]]
                for item in cls.DATABASES
            }
````

I think this works?

**Comment by bittner** [comment]
We should add @remeika's solution to the docs via https://github.com/jazzband/django-configurations/issues/36#issuecomment-445610301.
